### ISSUE TITLE
Everything integeration as alternative search engine

### ISSUE THREAD

**Issue by RedIODev** [files-community/Website#107]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

Files does everything I could wish from a file explorer. Tabs, ease of use, good design... but there is 1 thing witch is a dealbraker for me. It uses the windows search. And as we all know that thing is slow and good for nothing. So my idea would be to make an option to change the search to use [Everything](https://www.voidtools.com/). A free alternative search engine with suport for 3th party integration. It searches and finds files instently and is in my opinion the best search running on windows. It would be a great addition in my opinion and I don't think it would be a hard thing to implement for you judging by the brilliant look and feel Files presents itself with.

**Comment by TheOnlyTails** [comment]
This is the website repo, please open this issue on the app repo instead.
