### ISSUE TITLE
Add localization rules

### ISSUE THREAD

**Issue by onein528** [files-community/Website#109]
### What's the Problem?

Japanese translation of Files differs depending on the resource provider.

### Solution/Idea

I think we should create TranslationRules.svx file with each language section on files.community website.
Contain this:

1. Localization rules for each language.
2. The list of each localizarion reviewers(needs to be confirmed by the native speaker).
3. Any of the following:
    1. If contributer provides localization resources, Files members will mention to this docs to make sure they follow the rules.
    2. Create an issue template for localization and check the checklist to see if you follow the rules.
    3. List resource providers in each language as reviewers in Docs from previous contributions.

### Alternatives

If this is required only in Japanese, activate 3.3.

**Comment by onein528** [comment]
@yaichenbaum How do you think? it's good?

**Comment by yaichenbaum** [comment]
@onein528 I think we can add this link to the documentation to https://www.microsoft.com/en-us/language/styleguides

**Comment by onein528** [comment]
hmm...
okey. It is difficult and redundant to understand even from a native perspective.
How do you @h1g0 think?

**Comment by h1g0** [comment]
I' m new to this OSS community and not familiar with the detailed rules, but my thoughts are as follows:

- Basically, I think it's fine to follow the [Microsoft guidelines](https://www.microsoft.com/en-us/language/styleguides) above.
- However, it is preferable to have a page or file that can briefly describe the content and rules discussed in previous PRs and Issues.
- I also think that having a page or file where localization reviewers can be listed would simplify the review process and improve the quality when new localization PRs are created.

**Comment by onein528** [comment]
it is same as what I think.

**Comment by onein528** [comment]
How about assigning @h1g0 or @onein528 when someone providing ja-JP resources?

**Comment by yaichenbaum** [comment]
@onein528 I'm only able to request reviews from people in the Files org, the best thing to do is keep an eye on open pull requests to see if there is something that you'd like to review.

**Comment by onein528** [comment]
Sorry, I dont know very well about organization privileges. so please continue by a non-member way to get app id/secret.

**Comment by onein528** [comment]
![B20F5232-B5B2-4F77-B8C4-0D0CD3FF522C](https://user-images.githubusercontent.com/62196528/150436898-29588d9c-1b59-435c-b65d-8ce522af521b.png)

 we may be use this. you can access this page(your access role is ‘Maintain’)?

**Comment by onein528** [comment]
mention too?

If that's the case, I found out that I can't achieve the goal, so I'll go to see the PR regularly.
