### ISSUE TITLE
Cannot download sideload package

### ISSUE THREAD

**Issue by DrPepperBianco** [files-community/Website#115]
From this page "https://files.community/" I click on "Sideload Package". But instead of downloading this package (for instance to install it on an offline computer) the page instead opens a dialog "This site is trying to open App Installer". If I confirm it directly opens the App Installer, but I still didn't get the package.
I inspected the page with "F12" but I didn't found a link or something to download the package.

**Comment by DrPepperBianco** [comment]
Interestingly, I found the link "https://filescommunity.blob.core.windows.net/files/stable/Files.Package.appinstaller" when I clicked on "View Source" instead of "F12" (until now I always thought F12 would also show the source, which is obviously not true).

Still, it should be easier to download the file (although it's just an xml file with uris for other web resources, therefor it's not able to use it for offline installation anyway.

I downloaded the msixbundle file that was linked in the appinstaller file and could install this.

**Comment by TheOnlyTails** [comment]
> If I confirm it directly opens the App Installer, but I still didn't get the package.

The `ms-appinstaller` protocol doesn't work right now, there's nothing we can do about it.

**Comment by DrPepperBianco** [comment]
> The `ms-appinstaller` protocol doesn't work right now, there's nothing we can do about it.

Well of course you can: https://docs.microsoft.com/en-us/windows/msix/app-installer/installing-windows10-apps-web

Instead of calling "ms-appsinstaller:" link, just let us download the `msixbundle` instead. With this, the software can be installed on an offline machine (as long as all dependencies are fullfilled or also installed via msixbundle).
