### ISSUE TITLE
Page crashes when you click on `Docs`

### ISSUE THREAD

**Issue by crapStone** [files-community/Website#118]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Description

When you click on `Docs` and then on any other tab in the navigation bar, the site crashes and you have to refresh the page to use it again.

### Steps To Reproduce

1. click on `Docs`
2. click on `Blog`
3. try to click on `Docs` again -> not working anymore

### Expected behavior

I can navigate freely.

### Relevant Assets

![image](https://user-images.githubusercontent.com/23100555/150614027-29fe0b26-c094-4892-aeb4-e28dc53490c2.png)

**Comment by TheOnlyTails** [comment]
Is this in the main website or only in the #108 PR?

**Comment by crapStone** [comment]
The main website

**Comment by TheOnlyTails** [comment]
Can't replicate, closing.

**Comment by chingucoding** [comment]
Reopening this issue, I can reproduce this with the public website.

**Comment by Korkman** [comment]
This happens when clarity.ms is blocked for example by uBlockOrigin or Firefox Tracking Protection (when set to be more strict)
