### ISSUE TITLE
Сompact list of files

### ISSUE THREAD

**Issue by tsvetnoff** [files-community/Website#120]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

It would be good to add a compact format of files list identical to the standard Windows 11. This contributes to a smoother transition from the standard Explorer to Files. Imho it is too fat for large folders for now.

**Comment by TheOnlyTails** [comment]
This the website repo, not the app repo.
