### ISSUE TITLE
Overlapping Text

### ISSUE THREAD

**Issue by X86-7** [files-community/Website#14]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Description

On the features tab, when **File Preview**, you'll notice that the example provided to the left has a example file with overlapping text underneath it. It's titled _**June 2018**_.

I'd suggest adding something else or figuring out the scaling issue.

### Steps To Reproduce

1. Go to the website
2. Scroll down to the features area
3.  Click on File preview
4. Take a look at the example to the left.

### Expected behavior

It should scale it correctly and not overlap.

### Relevant Assets

![image](https://user-images.githubusercontent.com/84218614/135910057-f09edcef-2632-46ab-a638-98f9a3dc6a96.png)

**Comment by Tropix126** [comment]
Think the best course of action here is to ellipsis the text.

**Comment by TheOnlyTails** [comment]
I already have another solution, I posted it in the web dev channel on Discord, and I think you'll like it more.

**Comment by TheOnlyTails** [comment]
Will be fixed with #17 (this will be an interesting one!)
