### ISSUE TITLE
Save view as default

### ISSUE THREAD

**Issue by hiharry** [files-community/Website#143]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

It would be awesome if there were a "save view as default" button. Here's two scenarios this would be really awesome:
1. If I wanted to always see my folders using the column view, I would have to manually change to that view every time I enter a "root" folder. This is not that painful because we don't really have many "paths" we use daily as we tend to go the same folders over and over again. But it would be helpful anyway.
2. The name column is too short on my window and I have to make it bigger in every single folder. That is really painful. Lol. Here's an example: 
![image](https://user-images.githubusercontent.com/444878/152703003-a2cf3e91-a628-4908-b10a-d3d840204830.png)

Thanks a lot for the effort in making Files.

**Comment by chingucoding** [comment]
Thank you for creating this issue @hiharry, however this repository is for the website of Files, not Files itself. Please create a new issue on the [Files repository](https://github.com/files-community/Files).

**Comment by hiharry** [comment]
Sh*t. I didn't see I was in the wrong place. Sorry about that.
