### ISSUE TITLE
Dragging a File into a Folder Doesn't Work

### ISSUE THREAD

**Issue by BeholderVee** [files-community/Website#151]
Often, when I try to move a file by dragging it over a folder, my mouse pointer changes to a crossed red circle, and the file refuses to be moved. I have to double click the folder to enter it, return back, then it will work.
This doesn't happen to every folder at once, some folders will still accept files at the same time as other exhibit this behaviour.

**Comment by chingucoding** [comment]
Hi @BeholderVee , thank you for filling this issue! However this repository is for the website of Files, please create issues for Files on the [Files GitHub repository](https://github.com/files-community/files). Thank you!
