### ISSUE TITLE
STL Thumbnails

### ISSUE THREAD

**Issue by HALFxAxHEART** [files-community/Website#156]
Stl file thumbnails will not display the file with MS 3d viewer. When in normal file explorer it displays perfectly.

![file](https://user-images.githubusercontent.com/47039975/153980122-551311e3-30d0-47a7-bfbd-194d2bbfdca7.PNG)

![Files](https://user-images.githubusercontent.com/47039975/153980124-78b1e9f3-4fc2-464a-9b4b-9e292064e890.PNG)

**Comment by TheOnlyTails** [comment]
Hello, this repo is for Files' website. Please open this issue again on the app's repo.
