### ISSUE TITLE
Issue registering Files as default file manager

### ISSUE THREAD

**Issue by ColtMorgan** [files-community/Website#158]
After registering Files as the defualt file manager, I have encountered an issue a few times where the computer will think that the Windows Key is being held down. Any usage of the keys on the keyboard will register as Windows Key + E which will just result in opening multiple tabs of the Files application. Unregistering the application as the default file manager will resolve the issue.

**Comment by TheOnlyTails** [comment]
Hello, this repo is for Files' website. Please open this issue again on the app's repo.
