### ISSUE TITLE
The sideload packages on the website are interchanged

### ISSUE THREAD

**Issue by gotumjee** [files-community/Website#159]
When downloading Files, the "Sideload Package (Preview)" option takes the user to the stable version of the Files app and vice-versa.

**Comment by TheOnlyTails** [comment]
Weird, I can't reproduce this.

**Comment by gotumjee** [comment]
It seems to appear when trying Sideload Package and then Sideload Package (Preview). It does appear to be hard to reproduce though with seemingly random behavior upon each attempt.

**Comment by Arno989** [comment]
I've had this issue as well just now
