### ISSUE TITLE
Background is not acrylic, its slightly transparent.

### ISSUE THREAD

**Issue by X86-7** [files-community/Website#16]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.

### What browsers are you seeing the problem on?

Firefox

### Description

When looking at the previewed images of Files V2, the front of the landing page and part in front of the Windows 11 Background is strictly 50% transparent and theres no blur, like it is on other browsers.

### Steps To Reproduce

1. Go to the website
2. Take a look at the first part of the landing page
3. Take a look under the landing page where it says **Power meets beauty.**

### Expected behavior

The background should have a Gaussian blur.

### Relevant Assets

Left is Firefox, Right is Microsoft Edge

![Screenshot (3)](https://user-images.githubusercontent.com/84218614/135911996-232aa699-3816-4590-8152-84082d974d5b.png)

**Comment by TheOnlyTails** [comment]
The background blur here relies on the `backdrop-filter` CSS property, which is locked behind a flag in Firefox, meaning we can't fix this.
