### ISSUE TITLE
Default app

### ISSUE THREAD

**Issue by FikaMano** [files-community/Website#174]
Hey! I cant make it default app! 
![kép](https://user-images.githubusercontent.com/100856080/156588082-68893641-6cee-4bd1-a88d-8b7a9d154c9e.png)
Can you help me?

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.

**Comment by chingucoding** [comment]
As @TheOnlyTails correctly pointed out, this repository is for the Files App. Regarding your question, did you happen to install the Microsoft Store version of the app? If i recall correctly, only the sideloaded version of the app allows you to set Files as the default file explorer.
