### ISSUE TITLE
Modern File Manager not showing correct folder size

### ISSUE THREAD

**Issue by StauceanuSamuel** [files-community/Website#177]
Hey everyone.
These days i found an issue with files app - modern file manager. The issue is that the folder size is not displayed correctly. 

 
![Modern file manager](https://user-images.githubusercontent.com/82712305/156881765-fa502ca7-0a13-40d1-95e7-50e20e7dcd71.png)
![file explorer](https://user-images.githubusercontent.com/82712305/156881768-23263380-e0a3-40c9-aa56-ae36616dae6c.png)

In this 2 screenshot you can see that the same folder has 2 different size.
I am the only one with this problem? 
Version: 2.1.15.0
OS Version: 10.0.22000.527

Regards, 
         Samuel

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
