### ISSUE TITLE
Hey seem to have found a bug causing the Files progam to break.

### ISSUE THREAD

**Issue by Scoutey** [files-community/Website#178]
i simply pressed Delete key on 2-3 image files in my documents folder and it breaks my the program and it wont work without a restart.  as i click it showes the usual delete dialog but it instantly dissapairs and so does the open files window. when trying to open any folder it gives this msg
![Bilde_2022-03-08_192226](https://user-images.githubusercontent.com/101210419/157301288-a6f0b4c6-ef38-4a3e-b25e-bcf6f91393c7.png)

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
