### ISSUE TITLE
`isWindows` always evaluates to false for some reason

### ISSUE THREAD

**Issue by Tropix126** [files-community/Website#18]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.

### What browsers are you seeing the problem on?

Chrome

### Description

The `isWindows` variable seems to be failing to detect the user agent and always redirects to the store's web interface while using the download button.

### Steps To Reproduce

1. Click the download button with the store option pressed.

### Expected behavior

Download button should adapt to the user's operating system and either open the store app through a protocol or open the store's web interface depending if `navigator.platform === "Win32"` or `Win64`.

### Relevant Assets

none

**Comment by TheOnlyTails** [comment]
What does `navigator.platform` evaluate to then?

**Comment by TheOnlyTails** [comment]
Will be fixed with #17.
