### ISSUE TITLE
A Few Bugs

### ISSUE THREAD

**Issue by Illiter4ti** [files-community/Website#180]
- Files will crash often
- Sometimes cannot drag files between folders
- When able to drag items between folders, items will not show up immediately or until the directory is refreshed
- Cannot drag files from Files window into drag and drop file uploads on websites
- Files will act as if items in the left pane are being clicked randomly

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
