### ISSUE TITLE
Selection of Files/Folders via Hovering Mouse Over

### ISSUE THREAD

**Issue by T3chminator** [files-community/Website#181]
I see that there is no way to select files/folders by hovering the mouse pointer over.

Also, there is no option to make Files the default file explorer but I found out that if I use the sideload version from the Files website, I have the option to make it default file explorer but not if I get it via the MS Store.

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
