### ISSUE TITLE
Fail to delete from a Google Drive shared drive

### ISSUE THREAD

**Issue by Oded-Techsee** [files-community/Website#185]
I am using Google's G-Suite with shared drives version: 55.0.3.0
The application fails to delete a file from a folder within a shared drive.

![image](https://user-images.githubusercontent.com/62839580/159258670-f41f8034-e5ea-4f2f-a7c1-3efa5f274153.png)

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
