### ISSUE TITLE
Keyboard shortcut for Preview Panel is ```Alt + P```, not ```Ctrl + P```

### ISSUE THREAD

**Issue by co-bbrzgruppe** [files-community/Website#187]
… which is especially important as <code>Ctrl + P</code> [crashes the Files app completely](https://github.com/files-community/Files/issues/8371).

Please update https://files.community/docs/configuring/keyboard-shortcuts .

**Comment by yaichenbaum** [comment]
Ctrl + P is the correct shortcut, alt + p works as well since it's set as the access key.
![image](https://user-images.githubusercontent.com/39923744/160006355-31487de3-db92-4d77-a5b7-17ff74f1487f.png)
