### ISSUE TITLE
Cannot copy and paste an MP3 file from Windows to a Raspberry Pi

### ISSUE THREAD

**Issue by whashburn** [files-community/Website#191]
Hi - I apologize in advance that I am a Linux/Raspberry pi light weight so we might have to have several discussions to provide you with all of the information you need.

First of all - thank you for Files.  I really like the program and I appreciate everyone's efforts.

I have an extensive library of MP3s on a multi-folder library on a SSD that is my pi's /root.   I until installing Files I have always cut & pasted MP3s from my Windows iTunes music library to a subfolder on the pi.  Regardless of using Windows CTRL-C / CTRL-V or the icons provided by Files I cannot copy and paste an MP3 file.   I *can* copy and paste text files, just not MP3 files.

SMB was set up so I can access the folders on the pi from my Windows machines.

What other information do you need that I can try to provide.  

Hank

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.

**Comment by whashburn** [comment]
Sorry for my error.
