### ISSUE TITLE
Download files button's subtitle is equal to undefined

### ISSUE THREAD

**Issue by babakfp** [files-community/Website#204]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

![Screenshot 2022-05-16 122336](https://user-images.githubusercontent.com/44144724/168667328-2b0f5197-5b25-4437-aecb-4e1b803611bc.png)

### Expected behavior

I don't know

**Comment by babakfp** [comment]
https://user-images.githubusercontent.com/44144724/168668457-ac92333d-054f-455e-8c5e-2826038f8fc0.mp4

For a second it says "Microsoft Store". I cloned the repo on my system and it works fine in localhost:

![Screenshot 2022-05-16 123512](https://user-images.githubusercontent.com/44144724/168668753-1b17b785-8497-4273-bd66-72f7eb3eb8c9.png)

**Comment by babakfp** [comment]
Hmm, I removed the cookies and it works fine now🤷‍♂️

**Comment by yaichenbaum** [comment]
@babakfp please let us know if it happens again.
