### ISSUE TITLE
Failed to get GitHub contributors

### ISSUE THREAD

**Issue by babakfp** [files-community/Website#205]
Related to `contributorRows` in the source code.

```
{message: 'API rate limit exceeded for 89.38.99.93. (But here…t. Check out the documentation for more details.)', documentation_url: 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}
```

![Screenshot 2022-05-16 130514](https://user-images.githubusercontent.com/44144724/168673442-08f771f1-4964-4852-bdac-2759e89372f0.png)

---

Great job by the way😄🔥

```
{:catch err}
  {#each Array(35) as _}
    <Contributor
      html_url="https://github.com/yaichenbaum"
      avatar_url="data:image/svg+xml;{encodeURIComponent(Profile)}"
      contributions={0}
    />
  {/each}
{/await}
```

**Comment by babakfp** [comment]
> whats that

?

**Comment by onein528** [comment]
GitHub API without token has limits. So if you reload the web many times, it happens. This is not website bug

**Comment by onein528** [comment]
@yaichenbaum Close this.
