### ISSUE TITLE
设置默认文件管理器

### ISSUE THREAD

**Issue by Takaci** [files-community/Website#210]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

没有默认文件管理器开关，去哪下载sideload version

### Alternative solutions

增加设置默认文件管理器

### Relevant Assets

![image](https://user-images.githubusercontent.com/102419016/169744838-009a2015-fcbf-46f8-982c-7aefa8cb4266.png)

**Comment by yaichenbaum** [comment]
As noted in the screenshot, this option is only available in the sideload version of Files https://files.community/download/preview.
