### ISSUE TITLE
Alternate location for the "default User Folder"

### ISSUE THREAD

**Issue by AsHalt** [files-community/Website#211]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

Currently using store version of the App. 

my Start setting location for the default folders (Documents, Downloads, Music, Pictures, Videos) are not located on C:\\ ( C: drive ), and nor I want to store it on OneDrive (as _Files App_ is defaulted to currently)

normal File exe. (W11) works as planned, and is able to change location if i so choose.

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
