### ISSUE TITLE
Sideload installer does not work

### ISSUE THREAD

**Issue by ddattee** [files-community/Website#215]
Hi,

The sideload installer doesn't seem to be working because the CDN URLs don't seem to be accessible.
I've tried using the sideload, preview and winget to install it but I can't get the installer to work.

Am I missing something ?
Thanks

**Comment by yaichenbaum** [comment]
@ddattee can you post a screenshot of the issue?

**Comment by ddattee** [comment]
I would but couldn't reproduce the error.
When it occured the URL in the XML were not accessible even by hand so the install launcher was failing. It just worked so this issue can be closed. 
Thanks for the reply thought.
