### ISSUE TITLE
Drag and drop into app window doesn't work.

### ISSUE THREAD

**Issue by sobear69** [files-community/Website#219]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox

### Description

Drag and drop into app window doesn't work. Checked a couple of media players and office apps. When you try to drag and drop a file into the app window it either fails or doesn't do anything as Files is trying to copy/move the file.

### Expected behavior

Just like in normal explorer - drag and drop into an app window opens the file.

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
