### ISSUE TITLE
Bugs....

### ISSUE THREAD

**Issue by doobes** [files-community/Website#227]
First time user:

1) Sorting files by type doesn't.  I've got the sys internals files downloaded in a folder.  Sorting by type presents some of the executables, then compiled help files, then more executables.... 
2) File viewers? Excel/Word don't work, txt sort of works, displays some files but not others. Other files, that I've designated as text files (python scripts, batch files, etc) don't display.
3) Speed.  Who boy, this thing is slow...

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
