### ISSUE TITLE
Disk Space Is Not Updating! (BUG)

### ISSUE THREAD

**Issue by BrainyBuddies** [files-community/Website#229]
Hi, I've found a bug.
The bug is, that when I launch the files app, it's showing a disk space for example C:\\ 60GB, and when I clean my drive and free up some space(28GB), to update the disk space, I need to restart the app, it's not automatically updating the disk-space... for example if the disk space is 50GB and some changes happened like I installed an app in that drive, it needs to reduce 5GB but it's not doing it, it's showing the old value(50GB) and to see the real value, I need to re-open the app... but in native windows file explorer, you can see it's updating the disk-space continuously...
hope you understand...
thanks,
-BrainyBuddies(YouTuber)

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
