### ISSUE TITLE
win + E - AHK

### ISSUE THREAD

**Issue by Superjack78** [files-community/Website#23]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.

### What browsers are you seeing the problem on?

All browsers

### Description

https://files.community/docs/configuring/configure-win-e

Script is broken - missing "/" in AppDataLocalMicrosoftWindowsAppsiles.exe

corrected script is in expected behavior

### Steps To Reproduce

- Go to the docs page "Configuring Files to launch with the <kbd>Win</kbd> + <kbd>E</kbd> shortcut"
- View the code example

### Expected behavior
```ahk
; Win + E
#e::
FilesTitle := "Files ahk_class ApplicationFrameWindow ahk_exe ApplicationFrameHost.exe"
FilesLocation := USERPROFILE . "\AppData\Local\Microsoft\WindowsApps\files.exe"
    if WinExist(FilesTitle) {
        WinActivate % FilesTitle     ; Set focus
        SendInput ^t                    ; Send CTRL + t shortcut to open a new tab
    } else {
        Run % FilesLocation          ; Start Files
        WinWait % FilesTitle         ; Wait for it ...
        WinActivate % FilesTitle     ; Set focus
    }
return
```

**Comment by Superjack78** [comment]
> the same

What do you mean?

**Comment by Superjack78** [comment]
> > > the same
> > 
> > 
> > What do you mean?
> 
> I mean it happened to me the same as yours, BTW it seems to be solved in #22 it worked for me: change settings as follows.
> 
> `FilesLocation := USERPROFILE . "\AppData\Local\Microsoft\WindowsApps\Files.exe"`

Yep, in the Expected behavior heading I posted the correct script. (the person who posted it before me literally posted it one minute before me so when I wrote this there was no bug report yet)

**Comment by TheOnlyTails** [comment]
@Superjack78 Your corrected script is identical to the one in the docs.

**Comment by Superjack78** [comment]
> @Superjack78 Your corrected script is identical to the one in the docs.

@TheOnlyTails Did you look at mine and the website??? The script is literally broken without the \

My script 
FilesLocation := USERPROFILE . "\AppData\Local\Microsoft\WindowsApps\files.exe"

Website - https://files.community/docs/configuring/configure-win-e
FilesLocation := USERPROFILE . "AppDataLocalMicrosoftWindowsAppsiles.exe"
