### ISSUE TITLE
A tab for a timeline of things that are being worked on, left to do, etc.

### ISSUE THREAD

**Issue by GGProGaming** [files-community/Website#247]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

It would be wonderful to see what it is that has been finished, being worked on, or still in the backend. Just a neat feature to really push that this project is being actively worked on.

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
