### ISSUE TITLE
On server creating new folder creates multiple folders; disable default explorer ruins original explorer.exe

### ISSUE THREAD

**Issue by 2048bitDeveloper** [files-community/Website#254]
Hi,
I tried your app and it seems quite nice, however, there are two significant bugs.

1. On a server (at work, don't know any additional details) when I (as well as my colleague on a different machine) try to create a folder, Files creates two folders (folder, folder (02) with a modal that access denied, we couldn't create folder)/might be slightly different, I have the OS in czech language/
2. I switched Files to be the default Explorer, but after I couldn't create a shortcut from a server folder, I tried to switch it back, but since then I cannot open explorer.exe. I mean, the shortcut win+e and clicking explorer icon on the task bar gets me an error message, basically that explorer.exe could not be found and some other even shell stuff. I tried sfc/scannow and some stuff I found on the net to make it work, but with no success.

If you managed to solve these bugs, I would happily use this app, since the basic explorer sucks real hard.

Also, there is a minor bug. When clicked on a folder, the type becomes quite blurry and stays blurry even after I click on another folder, which becomes then blurry too.
Also, the color tags don't work on server files/folder. When I click on other folders and move back to the folder where I tagged a file, the color is gone.

And I have a suggestion. I unfortunately had to move from macOS and beside the column view I really miss the list view with triangles opening the folder exposing everything that's inside.
And could there be a possibility to make the type even smaller, it really takes a lot of estate.

Beside that I think it's a great app, I really love the tabs.

I'm learning to code, but still everything is jibrish to me and I have no clue how I would make such file manager, that would resemble the macOS Finder :)))

Thank you very much in advance for reply.

With kind regards

Jan Donath

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
