### ISSUE TITLE
High CPU usage and scroll stutter

### ISSUE THREAD

**Issue by hichemfantar** [files-community/Website#256]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

The website has unusually high cpu usage, while scrolling the cpu usage hovers around 30-40%.

Specs:
CPU: i5-10500H
RAM: 16GB

### Steps To Reproduce

1. Open chrome task manager using shift+esc
2. Scroll the website
3. Notice high cpu usage

### Expected behavior

Website should be very smooth considering It's mostly static.

**Comment by TheOnlyTails** [comment]
Can you try disabling the scrolling animations on the contributor cards and see if it makes a difference?

**Comment by hichemfantar** [comment]
I completely removed the contributors element from the dom using chrome dev tools and it has improved but I still feel that the CPU usage is unusually high.
It's sitting at 10% when not scrolling, I'm suspecting It's related to the background blur effects.
