### ISSUE TITLE
Restore windows file explorer.exe

### ISSUE THREAD

**Issue by MarkFeed** [files-community/Website#258]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Microsoft Edge

### Description

I tried files for a while but it really started slowing my machine.  Especially for typing.  I uninstalled, but now I get an error message that is some version of "application not found" when I try to use native explorer.exe. 

Any suggestions on how to get back to a working explorer?

### Steps To Reproduce

Uninstall
Reboot
Try to use explorer.exe 

### Expected behavior

Use native explorer.exe

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
