### ISSUE TITLE
Stable download link and preview are reversed

### ISSUE THREAD

**Issue by Av32000** [files-community/Website#263]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

On the home page of the site, in the drop-down menu for downloading Files, the ''Stable Version'' button sends to the download link for the preview version, while the ''Preview Version'' button sends to the download link for the stable version

### Steps To Reproduce

1. Go to https://files.community/
2. Open the drop-down menu
3. Choose between Stable and Preview

### Expected behavior

The Stable button links to the download link for the stable version and vice versa

### Relevant Assets

![image](https://user-images.githubusercontent.com/59660601/195672823-40d2a912-d006-42d1-8eaa-633f58c6fe81.png)

**Comment by TheOnlyTails** [comment]
@yaichenbaum can you take a look in the installers? I don't see anything wrong on the Svelte side.

**Comment by yaichenbaum** [comment]
@TheOnlyTails to reproduce
1. Download the sideload package
2. Download the sideload preview package and see it still downloads the sideload package

The correct way to fix this would be to stop saving the last option the user choose. The primary button should always be the store.

**Comment by TheOnlyTails** [comment]
@Tropix126 is there a chance you could make this change? I'm on vacation and won't have access to an editor for at least a week.

**Comment by Av32000** [comment]
I would like to point out that no matter which option is registered, the bug is always present

**Comment by Av32000** [comment]
Sorry I closed I had the wrong button

**Comment by Av32000** [comment]
The bug is still not patched on my side
