### ISSUE TITLE
Maybe remove note about firefox .xml to filename

### ISSUE THREAD

**Issue by soredake** [files-community/Website#267]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox

### Description

I'm using latest version of firefox on windows 11 and it does not add .xml to filename, so maybe it's better to remove this note?

### Steps To Reproduce

1. Install firefox from msstore
2. Go to https://files.community/download/preview
3. See note that does not represent current behavior in firefox.

### Expected behavior

No note about this.

### Relevant Assets

![image](https://user-images.githubusercontent.com/5204968/198678883-d5b71965-aeac-4cc2-9f05-d28bee7a1732.png)

**Comment by yaichenbaum** [comment]
@TheOnlyTails
