### ISSUE TITLE
Problema 

### ISSUE THREAD

**Issue by raul8505** [files-community/Website#270]
Hola al desarrollador está muy bueno este explorador pero cuando lo instale no me hace compatibilidad con el supercopier cuando copia y pego se abre su copiador por defecto por favor pudiera explicar esto y si tiene solución además la opción de (envíar a)no aparece cuando doy clip derecho en el menú contextual espero que lo arreglen para próximas actualizaciónes

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
