### ISSUE TITLE
"Size all columns to fit" option doesn't fit the columns permanently, after closing nd reopening File Manager columns goes to previous shape 

### ISSUE THREAD

**Issue by Shubhra29** [files-community/Website#272]
![Screenshot (5)](https://user-images.githubusercontent.com/117080524/198991368-549a8ea1-6e51-4a23-bee3-a693f3a7689e.png)

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
