### ISSUE TITLE
Files v2 bug/Problemes

### ISSUE THREAD

**Issue by ElyasAMZ21** [files-community/Website#273]
1: The file app can't be opened when minimized to the backround
2: It crashes
3: you can't drag "files/apps" and drop it to the file manager
4: It's laggy
5: opening files and folders take too long to execute

These problemes made me uninstall the programes

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
