### ISSUE TITLE
Edge function crashes when navigating to non-existent page

### ISSUE THREAD

**Issue by jack-weilage** [files-community/Website#274]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Firefox Beta/Dev/Nightly, Chrome Beta/Dev/Canary, Safari Beta, Microsoft Edge Beta/Dev/Canary

### Description

When navigating to a non-existent page, the Vercel Edge Function crashes and returns a `500: INTERNAL_SERVER_ERROR` instead of a `404: Not Found`.

For a temporary fix, disable Edge Functions in `svelte.config.js` by replacing [this line](https://github.com/files-community/Website/blob/2c9cee1de86692d303ee25b1de6ef788c59cafa8/svelte.config.js#L23) with `adapter: adapter()`.

### Steps To Reproduce

1. Navigate to a path like https://files.community/doesnt-exist.
2. See that the status code is `500`.

### Expected behavior

A `404: Not Found` error should be returned, and the contents of `+error.svelte` should be displayed.

### Relevant Assets

![image](https://user-images.githubusercontent.com/59130272/201491136-bc3e8d27-13cc-44f0-a655-b9945e2542b8.png)

**Comment by TheOnlyTails** [comment]
Fixed by #253
