### ISSUE TITLE
Preview appinstaller link is broken

### ISSUE THREAD

**Issue by RagibHasin** [files-community/Website#283]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Firefox Beta/Dev/Nightly, Chrome Beta/Dev/Canary, Microsoft Edge Beta/Dev/Canary

### Description

(https://files.community/appinstallers/Files.preview.appinstaller) points to preview version 2.3.45.0 from Oct 5, 2022, not the latest 2.4 announced on Nov 15, 2022.

### Expected behavior

(https://files.community/appinstallers/Files.preview.appinstaller) to point to the latest preview version, whatever that might be. Preferably automatically generated at each preview release.

**Comment by yaira2** [comment]
What happens when you open the appinstaller file to install the app, does it install the correct version?

**Comment by RagibHasin** [comment]
No, it installs version 2.3.45.0.

**Comment by NewtonChutney** [comment]
Hello, I see the issue still hasn't been solved?
Why has the maintainer closed the issue without a proper response? 
Since I can't reopen this, I'll be creating a new issue..
