### ISSUE TITLE
Separate projects from the website

### ISSUE THREAD

**Issue by codehangen** [files-community/Website#284]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

Hi all. 

I was wondering if you already thought about separating the website repository into "docs", "website", "themes", "blog", "locales". This allows only members of the files-community community to make changes to certain content without compromising the main content. *Have you all thought about separating the repository from the organization's website into separate repositories?*

### Alternative solutions

1. An alternative to this is to have separate branches: "docs", "website", "themes", "blog".
2. But... there may not be any organizational differences, as everything is organized in some way. *I said to separate the website repository into separate parts because it guarantees greater security for those who have access to certain things.* 

#### Idea
![image](https://user-images.githubusercontent.com/111701513/204060176-cf6e5191-70de-4e65-b57f-645f168c63b4.png)

**image-description:** As we can see in the image, we have separate repositories.

**Comment by yaira2** [comment]
All code changes are reviewed via a pull request before being merged, are there any benefits to separating the different sections?
