### ISSUE TITLE
Feature: Remove top section of home page

### ISSUE THREAD

**Issue by yaira2** [files-community/Website#287]
![image](https://user-images.githubusercontent.com/39923744/204410453-1412285a-1ed1-48b8-b132-273ce38ec2a6.png)

The top section of the home page is where we get to make the first impression for potential users, the current design is great, but we can make some minor adjustments to make it even better.

## Requirements
- Remove the top section of the home page
- In the "Power meets beauty" section, we should remap the primary button to link to a new download page where the user can select the version of the app they want to install.
    - The "Design system" link should be replaced with a "Learn more" link that navigates to the documentation page or alternatively, it can scroll down to the section of the home page where we highlight the best features.
    - The parallax animation direction should be reversed.

**Comment by TheOnlyTails** [comment]
This isn't done yet, the branch hasn't been merged.
