### ISSUE TITLE
Feature: Create new download page

### ISSUE THREAD

**Issue by yaira2** [files-community/Website#293]
Clicking the download button on the home page should link to a new download page

- There should be a prominent banner at the top of the page recommending the user sponsor the project
- Download page should contain three sections
   - Microsoft Store
   - Sideload
   - Preview
- Each section should contain the corresponding app icon and a description of the differences between versions.
- Each section should contain a download button
- Clicking download should stay on the page but it should display a progress bar and start the download

These changes will help make it easier for users to select the correct download and it'll also help with SEO.

**Comment by TheOnlyTails** [comment]
This isn't done yet, the branch hasn't been merged.
