### ISSUE TITLE
files bugs that makes the app unenjoyable

### ISSUE THREAD

**Issue by ChibaniJR** [files-community/Website#307]
1: can't scroll
2: tabs randomly open in other windows
3: files crashes
4: no icon preview in the taskbar
5: can't see the dark side of the copy, past and new folder menu
 and why don't you make the window rounded in windows 10?

Thank you for making this app

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
