### ISSUE TITLE
Features section suddenly changes selection while the user is interacting

### ISSUE THREAD

**Issue by dongle-the-gadget** [files-community/Website#321]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Microsoft Edge

### Description

The features section will suddenly change the feature selection while the user is interacting with the showcase.

This behavior can only be reproduced if JavaScript is enabled, because the automatic selection change is reliant on JavaScript.

### Steps To Reproduce

1. Scroll down to the Features section of the home page
2. Interact with the feature showcase for a long period of time (16 or 24, depending on whether you have clicked on the feature)
3. Notice how the showcase suddenly changes as you are interacting.

### Expected behavior

The showcase should pause scrolling until the user stops interacting with it for a prolonged period of time (say 3 - 5 seconds for instance).

**Comment by yaira2** [comment]
Feature section was redone so this is no longer an issue
