### ISSUE TITLE
Drag and Drop to a Dropbox folder fails with error message

### ISSUE THREAD

**Issue by schalli35** [files-community/Website#333]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Description

I always used drag & drop to upload files from the "Files" App to my dropbox opened within chrome (I do not use the dropbox app). While dragging file(s) the dropbox window normally got a blue dotted frame around the area where I could drop the file(s). Since the last "Files" update I do not get this frame.
While dropping the file(s) I get the error message (translated from german): "An empty file or an empty folder can not be uploaded." (tried Chrome and Edge - most current versions - failed in both).

It works well when I use the built-in windows file explorer (Chrome and Edge).

### Steps To Reproduce

1. Open your dropbox account and the folder where you want to drop file(s)
2. Open "Files" App
3. Drag a file (no matter which type of file)
4. Move it to the dropbox drop zone (-> blue frame does not appear)
5. Drop file
6. Error message appears

### Expected behavior

I expected the file(s) to be dropped correctly into the dropbox.

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
