### ISSUE TITLE
Blank : Startup settings  > Open a specific page or pages

### ISSUE THREAD

**Issue by badlyo** [files-community/Website#340]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

Blank when i click Add for Startup settings > Open a specific page or pages
I have windows 10 pro
Screenshot
![2023-01-15 18_56_59](https://user-images.githubusercontent.com/46354593/212559112-5306f0ce-c577-4162-a043-ee654c2a0f3b.png)

### Expected behavior

I hope it work open specific page or pages
Sory for my bad english

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
