### ISSUE TITLE
Feature: Add download link to the nav bar

### ISSUE THREAD

**Issue by yaira2** [files-community/Website#347]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

The download option is currently accessible from the home page but it's hard to discover from other pages. Adding a link to the nav bar should solve this issue.

**Comment by oleklukasiewicz** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/69370471/214418586-91880245-8a09-45b8-a160-594f1896d45d.png)

**Comment by yaira2** [comment]
Yes, except the background should be blue to grab users attention
