### ISSUE TITLE
Files v2.4

### ISSUE THREAD

**Issue by jer1825** [files-community/Website#352]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

O programa é muito mais lento quanto comparado com o nativo, principalmente ao abri-lo

### Expected behavior

No mínimo o aplicativo devia abrir rápido como file explor nativo do Windows.

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
