### ISSUE TITLE
Sync not included in cloud drives

### ISSUE THREAD

**Issue by decorex** [files-community/Website#355]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

Sync not included in cloud drives - app is not useful to me if it sync is not included

### Steps To Reproduce

Sync cannot be found in app

### Expected behavior

Sync to be included in app

### Relevant Assets

![image](https://user-images.githubusercontent.com/95507532/214482585-bb81b62e-f07e-4959-9726-0b2fd9909fa6.png)

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
