### ISSUE TITLE
Installer keeps running

### ISSUE THREAD

**Issue by skalwaghe-56** [files-community/Website#364]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

Hi, I was trying to install the app but the installer kept running please help into this.

### Steps To Reproduce

1.Downloads the setup file
2. Run the Setup

### Expected behavior

I expected it to install in 10-15 mins.

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
