### ISSUE TITLE
bug on files

### ISSUE THREAD

**Issue by ChibaniJR** [files-community/Website#382]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

I can't scroll, Why

### Steps To Reproduce

open files
go to any folder
can't scroll

### Expected behavior

maybe the new update

### Relevant Assets

no screenshots

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
