### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by DiscoveryOV** [files-community/Website#384]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

It would be great if releases could include a portable version of this app, if that's even possible. I would like to use it in a toolbox of sorts which requires running the application on-demand without the ability to install it.

**Comment by DiscoveryOV** [comment]
Currently I use Explorer++ for this purpose but Files is much more modern and incorporates nice features.

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
