### ISSUE TITLE
Favorites and Quick Access are empty

### ISSUE THREAD

**Issue by MarioPoier** [files-community/Website#394]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

When using the 2.4.48.0 version of Files on Windows 11 build 10.0.22000.1574 I have lost the ability to use the Favorites/Quick access. I've tried to uninstall and reinstall. I'm not sure of the location of any cache or configuration files that I could use to reset to default.

### Steps To Reproduce

1. Launch Files
2. Click on Favorites or view Quick Access

### Expected behavior

I would expect to see and be able to add/remove favorites and view/select quick access items.

### Relevant Assets

![image](https://user-images.githubusercontent.com/16354160/222216414-0bf73636-7f41-4418-a53e-1497076dc92d.png)

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
