### ISSUE TITLE
I can not click on item in show more options in contex menu

### ISSUE THREAD

**Issue by Under-Idea** [files-community/Website#400]
When you right click and show more options, you are unable to click on item that is in the level of window control buttons

### Expected behavior

Able to click on the item

### Relevant Assets

![image](https://user-images.githubusercontent.com/75729134/224093378-1ed73e76-a537-4c60-b82a-eb5f1585fd3a.png)
_If you have it like I have it in the picture, you will not be able to click on "Open in Terminal"_

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
