### ISSUE TITLE
Favorites not populating

### ISSUE THREAD

**Issue by gschlotthauer** [files-community/Website#404]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

I inadvertantly right clicked on Favorites and clicked Hide Favorites. After that Favorites disappeared. I re-instituted Favorites by Right clicking in the navigation pane. After that I couldn't pin anything to Favorites. If I am in home tab, Quick access gets populated but when I close the app and reopen and go to home tab there is nothing in quick access. This seems to be a bug. I uninstalled and did another install an problem was not fixed.

![Files bug](https://user-images.githubusercontent.com/127688206/224565597-d66919c1-51ec-46c0-b04e-d9e1af4abae6.jpg)

### Expected behavior

I expected that after I re-instated the Favorites tab it would populate as usual. If not, a reinstall should fix.

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
