### ISSUE TITLE
Broken donate link

### ISSUE THREAD

**Issue by csc530** [files-community/Website#412]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Other - list in description

### Description

The donate button link goes to https://www.paypal.com/paypalme/yaichenbaum which does not work. PayPal displays 
> We can’t find this profile
Make sure the link’s right and profile hasn’t been turned off.

Also tested it on: mypal

### Steps To Reproduce

1. Navigate to the download page, https://files.community/download
2. Click on the donate button
3. Be redirected to PayPal page https://www.paypal.com/paypalme/yaichenbaum

### Expected behavior

I'm not sure what donation platform you would use but a working link to support the developers/development

### Relevant Assets

For steps to reproduce:
step 2. ![image](https://user-images.githubusercontent.com/77406318/228726637-706184a6-a7a0-46a4-92bd-415c03ebd6c1.png)
step 4. ![image](https://user-images.githubusercontent.com/77406318/228726777-93d8016b-7d2b-4df0-b053-ca01f227a923.png)

**Comment by TheOnlyTails** [comment]
@yaira2 can you take a look at this?

**Comment by yaira2** [comment]
This has been resolved
