### ISSUE TITLE
Sort Folder/files by Date Last Accessed 

### ISSUE THREAD

**Issue by Tiffer777** [files-community/Website#415]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

When I access a directory, I would really love for it to be sorted by "Date Last Accessed".   "date last modified" doesn't do the same thing.

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
