### ISSUE TITLE
🐛 Blog: `svelte:head` displaying incorrectly client-side

### ISSUE THREAD

**Issue by Lamparter** [files-community/Website#424]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Microsoft Edge Beta/Dev/Canary

### Description

Most likely due to #414, the now-localised Metadata titles in the blog do not display correctly in a browser.
This error does not occur on any other page than the individual blog post page.

### Steps To Reproduce

1. Visit any blog post
2. View the page's title
3. See the error

### Expected behavior

Instead of displaying `{FilesName} • {title}` the website should instead display the localised version of `Files • Introducing Files, version 2.4.40` (or more appropriate blog post).

### Relevant Assets

![image](https://user-images.githubusercontent.com/71598437/236297223-650691c1-cf80-44bb-9907-ba9860ed7dd4.png)

**Comment by Joci1980** [comment]
98f40ffb2bcad27500f4b13e24a06e060e9d6467
