### ISSUE TITLE
Program won't install

### ISSUE THREAD

**Issue by MalcolmOgi** [files-community/Website#429]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox

### Description

Having downloaded the file using Classic Installer, on opening it, a window comes up with a maroon bar running from left to right which stays like that for several minutes, until I stop it. I've tried three or four times, including after rebooting my PC and downloading the program again, but with the same result. I've checked Firefox because this is my default browser, but I'm seeing this fault in Windows 11 not in a browser

### Expected behavior

The file to be installed.

**Comment by TheOnlyTails** [comment]
@yaira2 can you take a look?

**Comment by yaira2** [comment]
@MalcolmOgi this repository is specifically for the website. You can get assistance on our Discord server https://discord.gg/files.

**Comment by MalcolmOgi** [comment]
Thank you
Malcolm

**Comment by yaira2** [comment]
@MotionFXX you can find more resources on installing Files on our documentation page https://files.community/docs/install.
