### ISSUE TITLE
Combine Folders; Drag and Drop? 

### ISSUE THREAD

**Issue by bigboimarkus** [files-community/Website#436]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

Just like in regular windows. you had the power to combine folders without needing to replace or rename the folder.

### Alternative solutions

Make this a another option or a default option or by defualt when dragging and dropping with folders with the same name. 

### Relevant Assets

N/A

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
