### ISSUE TITLE
when opening the files app hangs for a few seconds and then loads things

### ISSUE THREAD

**Issue by tadkn** [files-community/Website#438]
Good evening, I use win 11 and I downloaded the app from the Microsoft store because the current native file explorer is not as good as it should be since the launch of win 11, but when opening the app it crashes for a few seconds and then loads the things however I don't know why these crashes are occurring when several other programs run without problems

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
