### ISSUE TITLE
Meu PC é bom mas ao abrir o explorador de arquivos com o aplicativo trava por alguns segundos

### ISSUE THREAD

**Issue by tadkn** [files-community/Website#439]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

Boa noite baixei o app pela loja da Microsoft pois o explorador de arquivos do Windows 11 não é tão bom como deveria ser desde o lançamento do novo sistema e depois de instalar o aplicativo eu defini ele como explorador de arquivos padrão porém toda vez que eu vou abrir O explorador de arquivos com o aplicativo eu vejo o que o aplicativo trava por mais ou menos 20 segundos e depois carrega as coisas mas eu gostaria de saber por que esse travamento sendo que com qualquer outro aplicativo em meu computador esse problema até onde eu já vi não ocorre ei eu gostaria muito de usar o aplicativo pois sem dúvidas é muito completo

### Steps To Reproduce

Baixei um aplicativo pela loja da Microsoft e abrir, Antes mesmo de definir o aplicativo como explorador de arquivos padrão eu Já notei que o aplicativo ao ser aberto trava por uns 10 ou 20 segundos e depois carrega as coisas e então só por esse fato Desse travamento eu fiquei bem triste e voltei pro explorador de arquivos Nativo

### Expected behavior

Se for algum tipo de bug sem dúvidas a gente espera que seja consertado o quanto antes porque pode ser que esteja acontecendo com outras pessoas

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
