### ISSUE TITLE
Broken horizontal scroll bar

### ISSUE THREAD

**Issue by onein528** [files-community/Website#44]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.

### What browsers are you seeing the problem on?

Chrome

### Description

![image](https://user-images.githubusercontent.com/62196528/139626537-f4ffdb3a-a394-4b59-9322-5e3f0d9df09f.png)

                                                    Broken ↑

### Steps To Reproduce

1. Go to https://files.community/docs/configuring/custom-themes
2. Set window size to 500px or less

### Expected behavior

It should be the same as the vertical bar.

**Comment by TheOnlyTails** [comment]
I'll get on it when I'm home.

**Comment by TheOnlyTails** [comment]
Will be fixed with #17.

**Comment by onein528** [comment]
See https://files.community/docs/contributing/building-from-source
Fix image size
