### ISSUE TITLE
windows file explorer stopped working

### ISSUE THREAD

**Issue by SergeySoloviov** [files-community/Website#453]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

After installing this software, windows file explorer stopped working.
Please help me to fix it.

### Expected behavior

that the default explorer will work

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
