### ISSUE TITLE
3 more options on the top ribbon bar

### ISSUE THREAD

**Issue by onlytanmoy** [files-community/Website#454]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

Great app as replacement of default win explorer, many thanks!

Just got one feature request, will it be possible to add the below options on the ribbon bar on the top?

- Copy Path
- Move To
- Copy To

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.

**Comment by onlytanmoy** [comment]
Sorry about that mate, logged the issue in the correct place now, thanks!
https://github.com/files-community/Files/issues/12635
