### ISSUE TITLE
Add bulk filename change

### ISSUE THREAD

**Issue by ivellios1988** [files-community/Website#460]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

I noticed Files doesn't let me change names of multiple files at once. I would really appreciate if you add this functionality.

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
