### ISSUE TITLE
Request to Fully Translate Website Content on Crowdin

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Website#467]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Firefox Beta/Dev/Nightly, Chrome Beta/Dev/Canary, Safari Beta, Microsoft Edge Beta/Dev/Canary, Other - list in description

### Description

I would like to know if it would be possible to have all the sentences on the website (documentation and news) fully translated on Crowdin.

### Expected behavior

Ensure that all website content, including documentation and news, is included in Crowdin

**Comment by Aditay2002** [comment]
@Lukiluc29 i will like to contribute towards this issue

**Comment by Lukiluc29** [comment]
Ultimately, after discussion, we will address this issue at a later time. However, thank you for your willingness.
