### ISSUE TITLE
TAG Label

### ISSUE THREAD

**Issue by giannibn** [files-community/Website#474]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox

### Description

labels don't work on pcloud.
If I put the labels on the mapped files of pcloud, when restarting the program they disappeared

### Steps To Reproduce

-

### Expected behavior

----

### Relevant Assets

---------

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
