### ISSUE TITLE
Open to Discussion: Should we remove the File Explorer replacement docs? 

### ISSUE THREAD

**Issue by TheOnlyTails** [files-community/Website#48]
Now that this option is built into Files with v2.0.33, do we really need a dedicated page for it? 

It should still be preserved so links won't break, but replaced with something like "go to settings, toggle the option"

**Comment by Tropix126** [comment]
If it's in the stable release now, we probably should.

**Comment by TheOnlyTails** [comment]
It is, but I feel like this should be discussed with @yaichenbaum before making a decision.

**Comment by yaichenbaum** [comment]
I feel that we should keep it for now since it includes the script to undo the changes.

**Comment by TheOnlyTails** [comment]
Maybe we should just modify it?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #91
