### ISSUE TITLE
MSword preview don't work

### ISSUE THREAD

**Issue by Massaing** [files-community/Website#488]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

MSword preview don't work 

### Expected behavior

MSword preview don't work

**Comment by chingucoding** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
