### ISSUE TITLE
Add documentation for FTP use

### ISSUE THREAD

**Issue by dwilbourn618** [files-community/Website#490]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

There is currently no documentation on the use of FTP in Files. Although this is apparently a standard function in Windows File Explorer it is not one I had ever heard of before and I had no idea it could be done in either program. Just documenting this function in Files would provide added value beyond the basic Windows File Explorer

**Comment by yaira2** [comment]
Thank you for the feedback
