### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by smudge3** [files-community/Website#493]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

Search feature only works if term that is searched is the first term in that filename

### Expected behavior

Term to be searched within the full filename, file type etc. as the standard windows explorer does

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.

**Comment by smudge3** [comment]
Apologies, and thanks.
________________________________
