### ISSUE TITLE
Files Does Not Show File Redirection

### ISSUE THREAD

**Issue by merrickville** [files-community/Website#497]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

(This does not pertain to a web browser)

I RDP into a Windows 11 running in a KVM (qemu) on Ubuntu 22.04.

On the Ubuntu host I'm using xfreerdp version 2.6.1 (2.6.1) for the RDP session into Windows 11.

On the Ubuntu host I start xfreerdp with the drive redirection switch:

```
xfreerdp \
  --many-cli-options.... \
  /drive:Home,/home/user \
  /drive:Root,/ \
  win11box.local:3389
```

Once logged into Windows 11, the "Files" application does list 'tsclient' under Network, but when clicked on a pop-up error:

Network folder error
Attempt to access invalid address.

On the Windows 11 original File Explorer, under "This PC" there is a section called "Redirected drives and folders". Yet there are my redirects from the /drive:Home,/home/user /drive:Root,/ command line switch.
These do not show up in the "Files" app.

Current Workarounds:
```
1) Manually enter into address bar:  \\tsclient\Home
2) set 'Files' as default & create desktop shortcut to \\tsclient\Home, double click on shortcut.
```
Only then can I view my drive redirections in the Files application. 

Is it possible to list any/all file/drive redirection in the GUI? Instead of having to type in to navigate to them manually?

### Steps To Reproduce

Log into Windows 11 KVM instance.
Launch File Explorer
Click "This PC" on navigation pane
View "Home" & "Root" folders in viewing pane

Launch "Files" 2.5.10.0 application.
Expand Network drives in navigation pane
  Click on 'Network' in Navigation Pane
  Double click on 'tsclient' in viewing pane

### Expected behavior

Unable to click "tsclient" to be able to see redirected/shared files using the RDP client.

Yes with Windows File Explorer 

No with Files 2.5.10.0

Must manually type into the "Files" app address bar:  
```
\\tsclient\Home or 
\\tsclient\Root 

```
to view shares.

### Relevant Assets

Files showing 'tsclient' folder...

![Files](https://github.com/files-community/Website/assets/34095609/c27b8495-1757-4b37-b6bb-21dd03ecdef7)

Error when opening (double clicking on) 'tsclient'

![Error](https://github.com/files-community/Website/assets/34095609/c7c75610-6aeb-46dc-8e3d-19e43c73580b)

In Windows 11 File Explorer, I can see my two redirected drives under "This PC" and able to double click to enter.

![File Explorer](https://github.com/files-community/Website/assets/34095609/17b6ab6d-81aa-46cb-b9b1-6b72fe23c11a)

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
