### ISSUE TITLE
Recycle bin icon

### ISSUE THREAD

**Issue by balkanio1** [files-community/Website#507]
### Before you start...

- [x] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

So when i right click on recycle bin icon and want to open it the icon on the left is default exe icon

### Steps To Reproduce

Open the Files app
Go to settings at top right
![image](https://github.com/files-community/Website/assets/123818298/2af0d7ff-b195-4d14-8ef1-a51debccad4e)
Press advance
![image](https://github.com/files-community/Website/assets/123818298/07ea5957-c46d-4511-a053-284ac45cc2f4)
Then enable experimental features
![image](https://github.com/files-community/Website/assets/123818298/723cc8d5-0784-401c-b0cb-da0a4a115299)
after enabling the icon on the left when u right click it become default exe icon

### Expected behavior

idrk what to say here

### Relevant Assets

![image](https://github.com/files-community/Website/assets/123818298/a7b75e4e-c7b8-4312-9cfd-53d308aac1c9)

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
