### ISSUE TITLE
Files sometimes doesn't start

### ISSUE THREAD

**Issue by Mattiuz93** [files-community/Website#517]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox

### Description

It happens that, when starting the PC with Windows 10, the app does not start showing a black screen. So I have to restart the pc to use it since a forced closure doesn't help either

### Steps To Reproduce

1. Start the PC
2. 2. Open the app

### Expected behavior

The application should open and function normally

### Relevant Assets

[debug.zip](https://github.com/files-community/Website/files/12291666/debug.zip)

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
