### ISSUE TITLE
App crashes after opening .zip files

### ISSUE THREAD

**Issue by jjongue** [files-community/Website#519]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Microsoft Edge

### Description

App crashes after opening a .zip file and selecting the files within.

### Steps To Reproduce

1. Set app to columns view
2. Open a zip file (via double-click)
3. Select a file within the zip file (crashes)

### Expected behavior

The expected behaviour is to allow the user to select and extract the files within a .zip file.

### Relevant Assets

![000033](https://github.com/files-community/Website/assets/141884406/4e32aaa4-860c-4dab-8eb1-a8039bb972b2)

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
