### ISSUE TITLE
Non-MS Store, Non-Admin download option

### ISSUE THREAD

**Issue by NewtonChutney** [files-community/Website#522]
Hello, I've been looking for a way to install your Files app in a PC which was forced to update to 11 by the IT dept, and the Store is blocked. Admin permissions out of scope too..
But I am able to install ms Store signed appx files though..

I hoped for the preview version to work, but I see a 2 KB file being downloaded which seems to a an xml file with dependencies and a pointer to the following URL.. 
`https://cdn.files.community/files/preview/Files.Package_2.3.45.0_Sideload_Test/Files.Package_2.3.45.0_x64_Sideload.msixbundle`

I notice a similar issue on preview URL had been closed without a proper response.. #283

**Comment by yaira2** [comment]
@NewtonChutney you can install Files without the store using the classic installer https://cdn.files.community/files/download/Files.Stable.exe

In the case of #283, the issue was resolved.

**Comment by yaira2** [comment]
@NewtonChutney did you try the preview installer? The version number in the appinstaller file doesn't mean anything.

**Comment by NewtonChutney** [comment]
Yes I did, I got a message saying the app was unable to start..

**Comment by yaira2** [comment]
Can you send a screenshot?

**Comment by NewtonChutney** [comment]
Yepp..
Here's screencap from OBS.. do rename it to .mkv, in case it doesn't open..
https://github.com/files-community/Website/assets/70827815/c34a9685-37d5-4cea-b3ce-94a188f1322f

**Comment by yaira2** [comment]
Unfortunately there isn't anything we can do about this, but the best action you can take from your side is to speak with your IT department about getting permission to install Files on your device.
