### ISSUE TITLE
Scroll to top after opening blog post 

### ISSUE THREAD

**Issue by AgentRBY** [files-community/Website#532]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Microsoft Edge

### Description

Currently if you open any of the bottom posts, the user will be at the bottom of the page, which is not good UX.

### Expected behavior

The user should be scrolled to the top after opening the blog page

### Relevant Assets

https://github.com/files-community/Website/assets/68181944/a47d3778-61a7-4f4a-aa01-c5f366530d36

**Comment by TheOnlyTails** [comment]
I'm looking into it as part of #527.
