### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by becadutra** [files-community/Website#545]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

Menu de instalação

### Steps To Reproduce

1 baixe o arquivo clássico
2 execute o arquivo de instalação
3 aperte instalar
4 após uns minutos o erro com a mensagem ''Falha na instalação. Entre em contato com o fornecedor de software.''
![Anotação 2023-09-23 183407](https://github.com/files-community/Website/assets/145875051/9e58e5c0-c806-4262-9c9d-67f1382e1e9b)

### Expected behavior

É esperado que a instalação prossiga com sucesso

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
