### ISSUE TITLE
Really bad performance on network folder with many files.

### ISSUE THREAD

**Issue by patricklabrie** [files-community/Website#551]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

When opening the network path, the process hang, and will come back but it takes quite a while. It's not responsive at all, I had to sadly uninstall it and use Windows again because of this. I'm quite sad.

### Steps To Reproduce

1. Go to Network folder.
2. Make sure the network folder has many files with folder that has many files recursively.
3. Observe it takes a long time to populate and is unresponsive.

### Expected behavior

Be quick and responsive. Ideally as quick as Windows Explorer.

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
