### ISSUE TITLE
I am run:pnpm run build, result: done ✓ built in 48.54s,but there is no index.html file found

### ISSUE THREAD

**Issue by duqingnian** [files-community/Website#556]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

when i run the pnpm run build command, just client and server folder in my disk:D:\Files\Website\.svelte-kit\output.
but i can't find the index.html in this 2 folder. please help me .or give me some tips.
thanks a lot!

### Expected behavior

.svelte-kit/output/server/entries/pages/download/_page.svelte.js                 24.41 kB
.svelte-kit/output/server/entries/pages/_layout.svelte.js                        27.39 kB
.svelte-kit/output/server/index.js                                               87.08 kB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-cloudflare
  ✔ done
✓ built in 48.54s

D:\Files\Website>npm run preview

> apicenter@0.0.1 preview
> svelte-kit preview

  ERROR
    Invalid command: preview

  Run `$ svelte-kit --help` for more info.

D:\Files\Website>

**Comment by TheOnlyTails** [comment]
see #557
