### ISSUE TITLE
locked tab

### ISSUE THREAD

**Issue by Shengwuei** [files-community/Website#559]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

hope some of the tabs can be locked, ie. when a tab is locked, double click the folders within the tab will open a new tab, instead of go into the folder in the same tab.

for example, assume I have the below folders :

D:\folder_a
D:\folder_a\folder_b

if I have a folder_a tab, and the tab is locked, within the tab if I double click folder_b, a new tab with folder_b is created instead of changing the tab from folder_a to folder_b.

This  feature is very useful for creating shortcuts of frequently used folders, would save a lot of time if these folders are within many levels of folder structure.

Thanks.

**Comment by yaira2** [comment]
@Shengwuei this repo is for the website, I think you're looking for https://github.com/files-community/Files.
