### ISSUE TITLE
Copying from a Phone ( FTP device ) Progress is not showing and too slow

### ISSUE THREAD

**Issue by daanish-manivannan** [files-community/Website#568]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

The files transfer from a mobile device or a camera doesn't show the progress 

### Steps To Reproduce

1. Go to files
2. Connect a mobile device or a camera
3. Switch to data transfer mode
4. Copy a file 
5. Paste it into system 
6. Progress doesn't show at all as only shows a task is placed

### Expected behavior

The progress should show with ETA and files directory should refresh fast

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
