### ISSUE TITLE
Refreshing and No shortcuts

### ISSUE THREAD

**Issue by whitemink2012** [files-community/Website#57]
I noticed that some shortcuts I have created (on a network drive) are not visible.  I use file explorer to verify they are there, but they do not show up in the same location in files.  Please fix this.

I noticed that I have to occasionally manually refresh a folder for a contents change to be seen.  Please make this automatic.

Version: 2.0.34.0
Windows 10

Files is amazing, please keep improving.

**Comment by TheOnlyTails** [comment]
This is the website repo, please create this issue on the repo for the app itself: https://github.com/files-community/files
