### ISSUE TITLE
Docs: Add Features docs section

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Website#582]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

Users can see easility what Files have and support and at the same time we can provide richer explanation when someone ask about a feature of Files app on Discord or somewhere else.

### Alternative solutions

None I believe.

**Comment by 0x5bfa** [comment]
I'd like to add if approved.

**Comment by yaira2** [comment]
Can you give some examples on how you would reorganize the existing docs?
