### ISSUE TITLE
Files application - lack of synchronization of remaining disk space in real time, and inability to drag files from the recently used section on the application's main page

### ISSUE THREAD

**Issue by Krzysztof23** [files-community/Website#585]
I downloaded program files about 2 weeks ago
After using it for a while, I noticed (at least on my computer) two moderately troublesome errors
   1 of them is the lack of real-time refreshing of disk capacity data, the refresh button (f5) does not work, a temporary workaround for me is to restart the system, but how long can it be done after each action changing the amount of available disk space?
   2 is the inability to drag and drop files from the recent files section on the main page, I don't know if it's a system limitation, a bug, or an oversight, but this function makes work much easier
 
Besides, I have tip and suggestion for adding things like QoL
   firstly, the disk capacity status bar could change color when the disk capacity reaches 90%, the program could also send a notification via the notification center

**Comment by yaira2** [comment]
Thanks for the feedback, this repo is specific for the Files website. You can find the repository for the app here https://github.com/files-community/Files/issues.
