### ISSUE TITLE
Installer fails

### ISSUE THREAD

**Issue by cbourner** [files-community/Website#588]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

I downloaded version 3.0.15.0 and ran the installer on Windows 11.

The installation halted after 5-10 seconds and displayed the message "Install failed.  Please contact your software vendor."

If there is any further information I can provide, please ask.

### Steps To Reproduce

Download installer here:
https://cdn.files.community/files/download/Files.Stable.exe

Run the installer.

### Expected behavior

Installation should complete.

### Relevant Assets

![2023-12-12 23 06 47](https://github.com/files-community/Website/assets/36651718/c12dee71-df49-460c-8b4e-de906a9c4314)

**Comment by rocky7x** [comment]
Hi,

Tried it today and got the same error. Windows 10.

**Comment by yaira2** [comment]
Does the preview version work?

**Comment by rocky7x** [comment]
Yes, the preview version works.

**Comment by yaira2** [comment]
What about the stable installer in the zip file? [Files.stable.appinstaller.zip](https://github.com/files-community/Website/files/13676886/Files.stable.appinstaller.zip)

**Comment by rocky7x** [comment]
Yes, that one works as well.

**Comment by yaira2** [comment]
Usually our custom installer works best but if it doesn't work, you can always use the installer I linked above.

**Comment by BentWrench** [comment]
Same issue on Windows 10. Launching dies not prompt for elevation of credentials to admin. Right-click the installer to run as admin results in "An error occured because a user was logged off". Install from zip archive works. Perhaps you could add a link to the Zip file on the downloads page?
