### ISSUE TITLE
Cannot set Specific Page to an Android folder

### ISSUE THREAD

**Issue by MtnWindows** [files-community/Website#597]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

In the Files app, I can browse to "This PC\GalaxyTabA7\SD card\Pictures\Instagram" but I cannot set that folder in Startup Settings to a Specific Page. If I browse for that folder under [+ Add page], it does not display GalaxyTabA7 in "This PC." I get an error if I enter the folder manually as a Specific Page. Incidentally, when I click on that folder in the Files App location box, it says "\\?\GalaxyTabA7\SD card\Pictures\Instagram" but that doesn't work either.

### Steps To Reproduce

1. Settings
2. Startup settings - Open a specific page or pages
3. + Add page
4. Try to browse to or paste in the Android folder "\\?\GalaxyTabA7\SD card\Pictures\Instagram" or "\\This PC\GalaxyTabA7\SD card\Pictures\Instagram"

### Expected behavior

Allow me to set that folder as a startup setting.
![Files-app-bug](https://github.com/files-community/Website/assets/12575963/849b167a-6084-436b-a5ae-581457a24845)

**Comment by yaira2** [comment]
Thanks for the feedback, this repo is for the Files documentation site. Please open an issue on the repo for the app https://github.com/files-community/Files.
