### ISSUE TITLE
No thumbnails available

### ISSUE THREAD

**Issue by ArexGermany** [files-community/Website#605]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

The app does not show thumbnails. I expected to see an individual small image of each photo . But I only see the same small  icon for all photos (.jpeg / .png / ...) 
<img width="770" alt="screenshot" src="https://github.com/files-community/Website/assets/156339486/5b2b5268-8563-4f9a-8384-8fde850f3766">

### Steps To Reproduce

1. Go to "Layout"
2. Click on "Mittelgroße Icons"

### Expected behavior

See small image of each photo.
<img width="770" alt="screenshot" src="https://github.com/files-community/Website/assets/156339486/c0fc7c1f-aae3-4652-86cf-dcc47af87724">

**Comment by TheOnlyTails** [comment]
This is the repo for the website, not the app. Please open the issue again in https://github.com/files-community/files.
