### ISSUE TITLE
Feature: Update tags documentation to include having to import the tags definition file.

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Website#616]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

Current it does not have this information so on other device they will show as unknown. Steps to do this should have both the import/export options method and manually copying the file, incase the user just wants only the tags and not other settings.

**Comment by yaira2** [comment]
This is resolved
