### ISSUE TITLE
Scrollbar on Files website is lagging

### ISSUE THREAD

**Issue by babakfp** [files-community/Website#62]
### Description

The main scrollbar is lagging and jumping...

### Steps To Reproduce

1. Go to [this website](https://files.community)
2. Scroll long-range (also short scroll) with a touchpad.
3. That's it.

### Expected behavior

Not lagging.

### Files Version

I don't

### Windows Version

Windows 10 Pro - 21H1 - OS Build: 19043.1320

**Comment by TheOnlyTails** [comment]
Do you mind recording your screen so we can see the issue?

**Comment by babakfp** [comment]
### Short scroll
Have an eye on the main content, you will see little lagging at the ending.
https://user-images.githubusercontent.com/44144724/141077577-9ae9937c-5f0b-4feb-9cc8-a709dffc1ce8.mp4

### Long scroll
Have an eye on the scroll bar.
https://user-images.githubusercontent.com/44144724/141077689-00b7fd1e-0f3e-4564-9208-d683964b136b.mp4

It's kinda hard to see, but its affects UX, you can feel the laggings...

**Comment by TheOnlyTails** [comment]
We only style the scroll bar, we don't control its scrolling pattern. This is probably an issue with your own system. I'm closing for now, unless someone else can replicate it.

**Comment by babakfp** [comment]
Maybe there are similarities to this bug:
https://youtu.be/C2kyxaQaXKc?t=597
