### ISSUE TITLE
[Animotica - Movie Maker & 1.1.92.0]: "Votica.exe" crash is observed while working with app function

### ISSUE THREAD

**Issue by Michellehdr** [files-community/Website#626]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Microsoft Edge

### Description

1. Schedule latest RS_PRERELEASE build.
2. Perform windows Updates.
3. Install the Animotica - Movie Maker & 1.1.92.0 from Store.
4. Launch Animotica - Movie Maker & 1.1.92.0
5. Work with the application.
6. Observe: App crash

### Steps To Reproduce

1. Schedule latest RS_PRERELEASE build.
2. Perform windows Updates.
3. Install the application from Store.
4. Launch the application
5. Work with the application.
6. Observe: App crash

### Expected behavior

Animotica - Movie Maker & 1.1.92.0 works normally

### Relevant Assets

Crash observed.

**Comment by Josh65-2201** [comment]
This is not the Animotica - Movie Maker issue tracker. STOP making issue on this.
