### ISSUE TITLE
Crashes on external monitor

### ISSUE THREAD

**Issue by FastFarmer** [files-community/Website#631]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

This works fine on the laptop screen, but as soon as you plug the external monitor in, it freezes then crashes. It wont run on an external monitor. Loads, sits there for a second, crashes. No idea how to even troubleshoot this?
It's shity though, No other app has a problem.

### Steps To Reproduce

Run it with external display

### Expected behavior

Ah, not to crash and be usable...

### Relevant Assets

ASUS TUF F15. I'm running Nvidia GeForce v551.61 in MUX so no idea if this is a graphics issue.

**Comment by Josh65-2201** [comment]
This repository is for the Files website. If it's an issue with Files please make a bug report here https://github.com/files-community/Files/issues/new/choose

**Comment by FastFarmer** [comment]
Oh. Yes it's a files issue.
