### ISSUE TITLE
How to quickly edit metadata for individual files?

### ISSUE THREAD

**Issue by GhostPoop** [files-community/Website#633]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

I bought the app hoping it would help me to edit my metadata, but it doesn't. I still have to click on Properties one by one to change the metadata. Is there a fast way to do this on Files? If not, can I get a refund?

**Comment by Josh65-2201** [comment]
Thanks for the question. This issue tracker is for the Files website. Please use https://github.com/files-community/Files/issues in future. 

Files can not edit meta data any faster then Windows File Explorer. Refunds are handled by Microsoft you will have to contact them

**Comment by yaira2** [comment]
> I bought the app hoping it would help me to edit my metadata, but it doesn't. I still have to click on Properties one by one to change the metadata. Is there a fast way to do this on Files? If not, can I get a refund?

You can select multiple files and edit the metadata together.
