### ISSUE TITLE
Insider preview package is broken

### ISSUE THREAD

**Issue by soredake** [files-community/Website#646]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox

### Description

![image](https://github.com/files-community/Website/assets/5204968/714da820-4638-4033-ace3-12ddfb759f91)

It's size is 1.6KB, after downloading it will give you error:
![image](https://github.com/files-community/Website/assets/5204968/c3582a3c-78e4-44ba-b072-9d868370f232)

### Steps To Reproduce

1. Go to https://files.community/download in firefox
2. Download insider preview
3. Run it
4. Error.

### Expected behavior

Working installer should be downloaded.

**Comment by Josh65-2201** [comment]
Thanks for the report, the install is working and should be that size. Please make sure you have app installer installed and updated via the Microsoft store or you can try
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/preview/Files.Package.appinstaller```
3. See if Files is in the start menu all apps section

**Comment by soredake** [comment]
Turns out my appinstaller was somehow broken, doing steps from this thread https://answers.microsoft.com/en-us/windows/forum/all/solved-when-i-try-to-open-any-appx-or-appinstaller/cf339756-1dfb-453f-bbf8-52fbbecffdc5 fix my problem, sorry!
