### ISSUE TITLE
Feature: Change the `compiling from source code` docs button to redirect to GitHub

### ISSUE THREAD

**Issue by Josh65-2201** [files-community/Website#654]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

To make sure that the information is up to date and save on duplication work, this link https://files.community/docs/contributing/building-from-source should redirect to GitHub's one https://github.com/files-community/Files?tab=readme-ov-file#building-from-source

**Comment by TheOnlyTails** [comment]
You could do this by adding this file:
```ts
// src/routes/docs/contributing/building-from-source/+page.server.ts
import type { PageServerLoad } from "./$types";
import { redirect } from "@sveltejs/kit";

export const load: PageServerLoad = () => {
	redirect("https://github.com/files-community/Files?tab=readme-ov-file#building-from-source");
}
```

**Comment by yaira2** [comment]
It would be preferable if we could mirror the two

**Comment by 0x5bfa** [comment]
Why not have a link to docs in GitHub readme instead?

## Installing and running

### Via Microsoft Store

Getting from MS Store enables you to donate us and be up-to-date every day through automatic update. This is the most preferable method.

// MS Store badge here

### Via our website

You want preview, you can’t access MS store, or you have an issue with installing from MS Store? We have preview version of Files. In addition, we also have an our own classic installer. Automatic are enabled in both as well.

// Our own badge?

### From source-code

You have to have some required components on Windows to build from the source-code. For more information, visit https://files.community/docs.

**Comment by yaira2** [comment]
> Why not have a link to docs in GitHub readme instead?

In theory that would work, but requiring people to click on a link reduces the chance of them following through.

**Comment by 0x5bfa** [comment]
Isn't that the same thing in files.community?

**Comment by yaira2** [comment]
I'm not sure what you're referring to, but there should be a way to mirror the shared markdown file.

**Comment by 0x5bfa** [comment]
Ah then it’s nice idea

**Comment by 0x5bfa** [comment]
We can close now?

**Comment by yaira2** [comment]
@Josh65-2201 we ended up linking to the docs page.
