### ISSUE TITLE
Bug: Typos in docs/customize-settings/appearance page

### ISSUE THREAD

**Issue by Vonarian** [files-community/Website#657]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome, Chrome Beta/Dev/Canary, Other - list in description

### Description

Using [Thorium AVX2 for Windows](https://github.com/Alex313031/Thorium-Win/) 123 on Windows 11.
Issues refer to this page: https://files.community/docs/customize-settings/appearance

1. "This allows you to change background color of the window." under the "Background color" section is missing a "the" before "background".
2. On the same line, "There is a large selection or pre-selected colors". **or** should be changed to **of**.
3. "Search for the any of the keys listed bellow". The "the" before any should be removed, bellow should be changed to below.

### Steps To Reproduce

Following the list in the Description section, you find the problematic section by:

1. Searching for "This allows you to change background color of the window."
2. Searching for "There is a large selection or pre-selected colors".
3. Searching for "Search for the any of the keys listed bellow".

### Expected behavior

1. **the** background
2. selection **of** pre-selected colors
3. Search for any of the keys listed below.

### Relevant Assets

![image](https://github.com/files-community/Website/assets/68429735/f10ebdcf-f830-4abc-bf52-95d116011311)

**Comment by yaira2** [comment]
Thank you for the report and fix in #658.
