### ISSUE TITLE
Sync tags between devices

### ISSUE THREAD

**Issue by Code2835** [files-community/Website#677]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

Need to sync tags between different computers.

**Comment by Josh65-2201** [comment]
Thanks for the feedback, In future please use the Files issue tracker https://github.com/files-community/Files/issues and not the website one for issue about the program.

Tags can already be copied between devices by exporting your settings in `Files settings > Advanced > Export` and then imported on the other computer in the same page. If you have further questions or issues join the discord https://discord.gg/files
