### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by HC1Gunner** [files-community/Website#694]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Other - list in description

### Description

I have a clean install of 10 Pro that is about a week and half old, I got sick of all the issues I was having with Win 11, went back to 10. About the only thing I missed from 11 was adding tabs in file explorer. I had Files installed and running, but then I discovered quick access was not working (zero history), so I uninstalled Files to start my troubleshooting. Took me a few days to figure out what the issue was, fixed, quick access is now working.
I decided to put Files back on 10, donated to your GitHub, download Files v3.6.0.0, ran the exe, and then ran as Admin, comes back with Install Failed. I thought about trying the Ms store, for install, but I don't want to turn around a pay again.
Donated to you via GitHub
https://github.com/sponsors/yaira2?frequency=one-time

### Steps To Reproduce

Run the exe for Files, with launch when install completes ticked.

### Expected behavior

The app to install.
![Install failed](https://github.com/user-attachments/assets/1b82ae05-6e73-43cf-ad1e-fcbf6d4a02cd)

**Comment by Josh65-2201** [comment]
Please use the Files issue tracker next time https://github.com/files-community/Files/issues

You can try
1. Opening PowerShell as administrator
2. Run this command
```Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller```
3. See if Files is in the start menu all apps section

**Comment by HC1Gunner** [comment]
Question I looked through the settings but could not see anything. When you copy/paste files or folders into "Files", is there any way to turn off where is ask if you want to replace existing, etc, I like to be able to turn that entire popup window off. I have my own file transfer app, and with Files, now its not even seen, like its be bypassed or something.

**Comment by Josh65-2201** [comment]
No, Files doesn't integrate with other transfer programs yet, but is planned.
