### ISSUE TITLE
Improving the site experience

### ISSUE THREAD

**Issue by d2dyno1** [files-community/Website#7]
This feedback is from the currently active site under the link:

- [x] Animations don't work on the "Docs" page
- [x] ~~Replacing Files with File Explorer description should be updated after an option to set it manually is present in Files Settings~~ Currently irrelevant, will be updated once such option is present.
- [x] (UX) The image on the blog page should be clickable
- [x] #99
- [x] The community badge background is barely visible

![image](https://user-images.githubusercontent.com/53011783/134957235-6693fbb2-25a0-4aa7-b1ee-e5a42add1c4e.png)
- [x] ~~When waited long enough on the Contributors section, the carousel will warp~~
- [x] ~~There still exists a bug when on "Blog" or "Docs" page the link is set to "Home" page~~ SvelteKit router bug
- [x] ~~The items in SplitButton dropdown ("Download Files") shouldn't be selectable~~
- [ ] Fade-in animation would be nice for themes selection

This is my feedback and issue reports. If any of these don't align with the plans for website, edit the comment and cross these items out :)

**Comment by Tropix126** [comment]
4 is partially done now.

**Comment by Tropix126** [comment]
So, I might have found a fix to 1, although I'll need to do a little testing. (relevant: https://github.com/sveltejs/kit/issues/628)

**Comment by Tropix126** [comment]
Everything on the list is now done. Should we close this?
