### ISSUE TITLE
"Phantom" USB drives, cannot be removed

### ISSUE THREAD

**Issue by WoSe2021** [files-community/Website#70]
I only discovered afterwards that USB drives that are not logged off before the computer is shut down remain under Files as "phantoms". These cannot be removed from Files and the drive letters are not reassigned by Windows 11. Unfortunately, uninstalling and reinstalling Files did not change anything. These phantom drives are not present in Windows Explorer, but the corresponding drive letters are also no longer available for assignment in Windows drive management. The USB drives E-H in the picture are such phantom drives.
![Screenshot 2021-11-16 183059](https://user-images.githubusercontent.com/94476095/142035966-534524f0-7906-412d-8f1b-b234eb377aa6.png)

**Comment by TheOnlyTails** [comment]
Please post this on the Files repo, this is the Website's repo.
