### ISSUE TITLE
Add ps1 files to vendor.yml.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Website#72]
At the moment, there are two powershell files stored in the repo that are pretty massive due to their signatures. This destabilizes the linguist statistics saying that the repo is around half written with powershell. Linguist can exclude files in the language statistics by adding them to a `vendor.yml` file.

**Comment by TheOnlyTails** [comment]
Actually, these two can be removed entirely, since this is now handled outside of the repo.

**Comment by TheOnlyTails** [comment]
Closed by #108.
