### ISSUE TITLE
Why does Desktop.Files.JSON keeps on showing up after I delete it?

### ISSUE THREAD

**Issue by WhosPruv** [files-community/Website#74]
I thought my laptop was infected with a virus but then I uninstalled "Files" and it was gone. Should I ignore them or is it a bad thing?

![ApplicationFrameHost_nRfraNwfma](https://user-images.githubusercontent.com/94924029/143071731-ce92fd1a-601e-46f4-996d-71d929775346.png)

**Comment by TheOnlyTails** [comment]
This is the website repo. Please post this issue on the Files repo: https://github.com/files-community/Files.
