### ISSUE TITLE
files.community links to website repo github not Files 

### ISSUE THREAD

**Issue by DejayRezme** [files-community/Website#78]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox

### Description

I was looking for the github for files and clicked on the bottom of the page to check out the source code and issues, but landed in the wrong repository

### Steps To Reproduce

1. go to https://files.community/
2. scroll down
3. click on github
4. make bug report
5. find out you're in the wrong github repo

### Expected behavior

link should go to proper github repo

**Comment by TheOnlyTails** [comment]
That's intended behavior. The correct link is placed higher up, in the navbar.
