### ISSUE TITLE
[Feature Request] F4 Keyboard shortcut to jump to 'address bar', similar to File Explorer

### ISSUE THREAD

**Issue by RaddedMC** [files-community/Website#79]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the website.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

Windows' existing file explorer lets you jump to the address bar by pressing F4 -- this was a super useful part of my workflow. I've switched to Files since it's way more stable than Windows 11's file explorer, but missing this keyboard shortcut is a bummer I think could be added fairly quickly.

**Comment by TheOnlyTails** [comment]
This is the website repo, please open this issue on the repo for the Files app: https://github.com/files-community/Files
