### ISSUE TITLE
Bug update file list and with Winrar

### ISSUE THREAD

**Issue by Micka974** [files-community/Website#80]
Hello,

I tried your sofware Files. It is really great !
But I encounter some problems. I will try to explain to you :

1) When I copy or move a file or a folder to another one, I always have to update with F5 the list if I want to view the file/folder copied
2) I use winrar to zip my files, and it seems impossible to grab and drop files to a zip file in the list of your software.

Thank you for your work, it is impressive

**Comment by TheOnlyTails** [comment]
Hello, this is the Files website repo. Please post this issue on the Files repo: files-community/Files
