### ISSUE TITLE
[site] Easy UX improvements

### ISSUE THREAD

**Issue by babakfp** [files-community/Website#81]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

Hi

### 1
Add a loading bar to the website https://files.community like https://skit.vercel.app

### 2
a 3000px image loading here. It's huge and it's not needed https://files.community/blog
Also, use this website https://imagecompressor.com/ to reduce the size of all images used in the website.
![Screenshot 2021-12-18 135733](https://user-images.githubusercontent.com/44144724/146656499-004b6dfd-f849-41e4-8db0-da527f3bc684.png)

### 3
Add `cursor: pointer` to this box https://files.community/blog
![Screenshot 2021-12-18 135554](https://user-images.githubusercontent.com/44144724/146656475-245de5ea-df67-4946-bf46-845f516fd256.png)

### Expected behavior

_

**Comment by TheOnlyTails** [comment]
I don't see any loading bar in https://skit.vercel.app. What are you referring to? 

I'll take care of the rest of the points in a later time.

**Comment by babakfp** [comment]
> I don't see any loading bar in https://skit.vercel.app. What are you referring to?

https://user-images.githubusercontent.com/44144724/146657630-9a224eb8-a0dc-4ab7-b137-4ddce037d429.mp4

**Comment by babakfp** [comment]
https://skit.vercel.app repo 👉 https://github.com/babakfp/sveltekit-docs

**Comment by yaichenbaum** [comment]
@babakfp issue 2 has been resolved.
