### ISSUE TITLE
ms-appinstaller scheme deprecation

### ISSUE THREAD

**Issue by rosegayming** [files-community/Website#83]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Microsoft Edge Beta/Dev/Canary

### Description

The `ms-appinstaller` url scheme was deprecated, meaning the sideload package buttons should now point directly to the MSIX package directly, rather than `ms-appinstaller:?source=` https://aka.ms/ms-appinstaller-disabled

### Steps To Reproduce

1. Open https://files.community/
2. Select sideload app from the download files dropdown
3. Try to open in App Installer

### Expected behavior

Downloads MSIX package, to be them installed using App Installer. 

### Relevant Assets

![image](https://user-images.githubusercontent.com/46611144/147036633-3f334f1b-088a-4ad2-9631-6f03bfebe658.png)

**Comment by yaichenbaum** [comment]
@rosegayming the scheme seems to have only been disabled [temporarily](https://techcommunity.microsoft.com/t5/msix-deployment/the-ms-appinstaller-protocol-has-been-disabled/m-p/3039448/highlight/true#M1100). In the meantime, you can download Files using the direct [path](https://filescommunity.blob.core.windows.net/files/preview/Files.Package_2.0.43.0_Test/Files.Package_2.0.43.0_x86_x64_arm64.msixbundle).
