### ISSUE TITLE
hidden files not show on network storage with show hidden files enable

### ISSUE THREAD

**Issue by JGomsss** [files-community/Website#86]
hidden files not show on network storage with show hidden files enable
view on explorer
![image](https://user-images.githubusercontent.com/28355812/147904876-180dda78-879a-4906-b001-49f878349920.png)
view  on Files
![image](https://user-images.githubusercontent.com/28355812/147904963-38b123fd-ab05-4cc9-8ccc-21619f0b4dbd.png)

**Comment by josh-65** [comment]
This is for the website of Files open an issues at https://github.com/files-community/Files/issues

**Comment by JGomsss** [comment]
redirect to FIles git
