### ISSUE TITLE
lnk files

### ISSUE THREAD

**Issue by DRI90** [files-community/Website#95]
I notice that the lnk files do not appear in Files while they are actually present in Explorer. Is an update planned
<img width="945" alt="Capture d’écran 2022-01-11 092312" src="https://user-images.githubusercontent.com/97507289/148906688-e5f0f1b7-58a8-4504-9a0f-935aedb41651.png">

**Comment by TheOnlyTails** [comment]
This is the website repo, not the app repo. please file an issue there.
