### ISSUE TITLE
Switch .svx files to markdown files.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Website#98]
Currently we use mdsvex's default extension for naming blog post and documentation entries, but we don't use many mdsvex-specific features. I think that it would be safe to configure mdsvex to read `*.md` files, then just use those so that GitHub picks up on the filetype.

**Comment by yaichenbaum** [comment]
@Tropix126 are there any mdsvex features that we could take advantage of?

**Comment by TheOnlyTails** [comment]
There are Svelte components in markdown, frontmatter metadata (which we use), layouts (we're using SvelteKit's layouts instead), and Remark plugins, which we also use.
Svelte components in markdown aren't really needed unless we need very custom content, and even then - MDSvex can be configured for any file extension. 
This will also allow GitHub to render the pages.

**Comment by Tropix126** [comment]
> @Tropix126 are there any mdsvex features that we can take advantage of?

I might clarify that these files will still be ran through mdsvex, they'll just have an extension that Github recognizes and can preview. At the moment we use some remark plugins and frontmatter (for blogpost metadata). Other than that, we don't really do any serious custom syntax.
